// Central glossary of analytics metric formulas & descriptions.
// Keeps UI tooltips consistent and enables reuse / potential localization.

export const metricsGlossary = {
  repeatCustomers: {
    label: 'Repeat Customers',
    formula: 'Customers with ≥ 2 orders in current period',
    description: 'Count of distinct customers who placed two or more orders during the selected period.'
  },
  repeatRate: {
    label: 'Repeat Customer Rate',
    formula: 'Repeat Customers / Total Customers',
    description: 'Percentage of customers in the period that placed at least two orders.'
  },
  ordersFromRepeat: {
    label: 'Orders from Repeat Customers',
    formula: 'Sum of orders placed by Repeat Customers',
    description: 'How many orders were generated by customers who ordered at least twice in the period.'
  },
  repeatOrderShare: {
    label: 'Repeat Order Share',
    formula: 'Orders from Repeat / Total Orders',
    description: 'Percent of orders attributable to repeat customers (depth of repeat engagement).'
  },
  retentionRate: {
    label: 'Retention Rate',
    formula: 'Retained Customers / Previous Window Customers',
    description: 'Percent of customers active in the previous equal-length window who also ordered in this period.'
  },
  churnRate: {
    label: 'Churn Rate',
    formula: 'Churned Customers / Previous Window Customers',
    description: 'Percent of previous-window customers who did NOT order in this period (1 - retention).' 
  },
  funnelPendingToProcessing: {
    label: 'Pending → Processing Conversion',
    formula: 'Processing Count / Pending Count',
    description: 'Share of orders created in the period that advanced from pending to processing.'
  },
  funnelProcessingToShipped: {
    label: 'Processing → Shipped Conversion',
    formula: 'Shipped Count / Processing Count',
    description: 'Share of processing orders that progressed to shipped within the period.'
  },
  funnelShippedToDelivered: {
    label: 'Shipped → Delivered Conversion',
    formula: 'Delivered Count / Shipped Count',
    description: 'Share of shipped orders reaching delivered status in the period.'
  },
  funnelOverallDelivered: {
    label: 'Overall Delivered Conversion',
    formula: 'Delivered Count / Pending Count',
    description: 'End-to-end conversion from initial pending to delivered within the period.'
  },
  cancellationRate: {
    label: 'Cancellation Rate',
    formula: 'Cancelled Count / Pending Count',
    description: 'Percent of orders created in the period that were cancelled.'
  },
  refundRate: {
    label: 'Refund Rate',
    formula: 'Refunded Count / Delivered Count',
    description: 'Percent of delivered orders in the period that resulted in a refund.'
  }
};

export function buildTooltip(key) {
  const entry = metricsGlossary[key];
  if (!entry) return '';
  return `${entry.label}: ${entry.formula} — ${entry.description}`;
}
